In [1]:
import pandas as pd

df = pd.read_csv("../data/imdb_dataset.csv")
print(df.columns)

df = df[['review', 'sentiment']].dropna()

#select only first 1000 data from dataset
df = df[:1000]
print(len(df))
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '../data/imdb_dataset.csv'

In [ ]:
#resources for NLTK and spaCy
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab')

import spacy

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/aakashshrestha/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/aakashshrestha/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/aakashshrestha/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/aakashshrestha/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [ ]:
#remove <br> </br> from the data
df['review'] = df['review'].str.replace(r'<br\s*/?>', '', regex=True)

In [ ]:
#tokenization
import nltk
from nltk.tokenize import word_tokenize

df['tokens'] = df['review'].apply(lambda x: word_tokenize(x))
df.head(10)

                                              review  ...                                             tokens
0  One of the other reviewers has mentioned that ...  ...  [One, of, the, other, reviewers, has, mentione...
1  A wonderful little production. The filming tec...  ...  [A, wonderful, little, production, ., The, fil...
2  I thought this was a wonderful way to spend ti...  ...  [I, thought, this, was, a, wonderful, way, to,...
3  Basically there's a family where a little boy ...  ...  [Basically, there, 's, a, family, where, a, li...
4  Petter Mattei's "Love in the Time of Money" is...  ...  [Petter, Mattei, 's, ``, Love, in, the, Time, ...
5  Probably my all-time favorite movie, a story o...  ...  [Probably, my, all-time, favorite, movie, ,, a...
6  I sure would like to see a resurrection of a u...  ...  [I, sure, would, like, to, see, a, resurrectio...
7  This show was an amazing, fresh & innovative i...  ...  [This, show, was, an, amazing, ,, fresh, &, in...
8  Encouraged by the positive comments about this...  ...  [Encouraged, by, the, positive, comments, abou...
9  If you like original gut wrenching laughter yo...  ...  [If, you, like, original, gut, wrenching, laug...

[10 rows x 3 columns]

In [ ]:
#case folding
df['tokens_lower'] = df['tokens'].apply(lambda x: [word.lower() for word in x])
df.head()

                                              review  ...                                       tokens_lower
0  One of the other reviewers has mentioned that ...  ...  [one, of, the, other, reviewers, has, mentione...
1  A wonderful little production. The filming tec...  ...  [a, wonderful, little, production, ., the, fil...
2  I thought this was a wonderful way to spend ti...  ...  [i, thought, this, was, a, wonderful, way, to,...
3  Basically there's a family where a little boy ...  ...  [basically, there, 's, a, family, where, a, li...
4  Petter Mattei's "Love in the Time of Money" is...  ...  [petter, mattei, 's, ``, love, in, the, time, ...

[5 rows x 4 columns]

In [ ]:
#stop word removal
from nltk.corpus import stopwords

stopwords = set(stopwords.words('english'))
print(len(stopwords))

df['tokens_nostopwords'] = df['tokens_lower'].apply(lambda x: [word for word in  x if word.isalpha() and word not in stopwords]);
df['tokens_nostopwords'].head(20)

198

0     [one, reviewers, mentioned, watching, oz, epis...
1     [wonderful, little, production, filming, techn...
2     [thought, wonderful, way, spend, time, hot, su...
3     [basically, family, little, boy, jake, thinks,...
4     [petter, mattei, love, time, money, visually, ...
5     [probably, favorite, movie, story, selflessnes...
6     [sure, would, like, see, resurrection, dated, ...
7     [show, amazing, fresh, innovative, idea, first...
8     [encouraged, positive, comments, film, looking...
9     [like, original, gut, wrenching, laughter, lik...
10    [phil, alien, one, quirky, films, humour, base...
11    [saw, movie, came, recall, scariest, scene, bi...
12    [im, big, fan, boll, work, many, enjoyed, movi...
13    [cast, played, appreciate, trying, bring, shak...
14    [fantastic, movie, three, prisoners, become, f...
15    [kind, drawn, erotic, scenes, realize, one, am...
16    [films, simply, remade, one, bad, film, fails,...
17    [movie, made, one, top, awful, movies, horribl...
18    [remember, film, first, film, watched, cinema,...
19    [awful, film, must, real, stinkers, nominated,...
Name: tokens_nostopwords, dtype: object

In [ ]:
#stemming

from nltk.stem import PorterStemmer
stemmer = PorterStemmer()
df['tokens_stemmed'] = df['tokens_nostopwords'].apply(lambda x: [stemmer.stem(word) for word in x])
df['tokens_stemmed'].head(10)

0    [one, review, mention, watch, oz, episod, hook...
1    [wonder, littl, product, film, techniqu, fashi...
2    [thought, wonder, way, spend, time, hot, summe...
3    [basic, famili, littl, boy, jake, think, zombi...
4    [petter, mattei, love, time, money, visual, st...
5    [probabl, favorit, movi, stori, selfless, sacr...
6    [sure, would, like, see, resurrect, date, seah...
7    [show, amaz, fresh, innov, idea, first, air, f...
8    [encourag, posit, comment, film, look, forward...
9    [like, origin, gut, wrench, laughter, like, mo...
Name: tokens_stemmed, dtype: object

In [ ]:
#Lemmatization
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
df['tokens_lemmatized'] = df['tokens_nostopwords'].apply(lambda x: [lemmatizer.lemmatize(word) for word in x])
df.head(10)

                                              review  ...                                  tokens_lemmatized
0  One of the other reviewers has mentioned that ...  ...  [one, reviewer, mentioned, watching, oz, episo...
1  A wonderful little production. The filming tec...  ...  [wonderful, little, production, filming, techn...
2  I thought this was a wonderful way to spend ti...  ...  [thought, wonderful, way, spend, time, hot, su...
3  Basically there's a family where a little boy ...  ...  [basically, family, little, boy, jake, think, ...
4  Petter Mattei's "Love in the Time of Money" is...  ...  [petter, mattei, love, time, money, visually, ...
5  Probably my all-time favorite movie, a story o...  ...  [probably, favorite, movie, story, selflessnes...
6  I sure would like to see a resurrection of a u...  ...  [sure, would, like, see, resurrection, dated, ...
7  This show was an amazing, fresh & innovative i...  ...  [show, amazing, fresh, innovative, idea, first...
8  Encouraged by the positive comments about this...  ...  [encouraged, positive, comment, film, looking,...
9  If you like original gut wrenching laughter yo...  ...  [like, original, gut, wrenching, laughter, lik...

[10 rows x 7 columns]