In [25]:
import pandas as pd

In [26]:
reviews = pd.read_csv("../data/employee_reviews.csv")
reviews.head()

  Employee Name                                             Review
0      Scarlett  So happy with the hybrid work policy! <u>under...
1         Chloe  <div>division content</div> The new intern is ...
2         Logan  <code>sample code</code> The new intern is doi...
3          Nina  Great onboarding process! <code>sample code</c...
4         Emily  Can someone check the broken AC in meeting roo...

In [27]:
#rename the columns 
reviews.columns = ['employee_name', 'review']
reviews.head()

  employee_name                                             review
0      Scarlett  So happy with the hybrid work policy! <u>under...
1         Chloe  <div>division content</div> The new intern is ...
2         Logan  <code>sample code</code> The new intern is doi...
3          Nina  Great onboarding process! <code>sample code</c...
4         Emily  Can someone check the broken AC in meeting roo...

<b>Tasks:</b>
1. HTML tags
2. URLs
3. Punctuations (!?)
4. Extra spaces
5. Emoji
6. Captial case (convert everything into lower case)

In [28]:
import re

def clean_text(text):
    # 1. remove HTML tags
    text = re.sub(r'<.*?>', '', text)
    
    #2. remove URLS
    text = re.sub(r'http\S+|www\.\S+', '', text)
    
    #3. remove punctuations and emoji
    text = re.sub(r'[^A-Za-z\s]', '', text) # ^ means except and \s means whitespace
    
    #4. remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip() #strip removes the whitespace at the beginning and end
    
    #5. remove emoji already at 3
    
    #6. lower case itttt
    text = str(text).lower()
    
    return text

In [29]:
reviews['cleaned_review'] = reviews['review'].apply(clean_text)
print(reviews['cleaned_review'].iloc[:10])

0      so happy with the hybrid work policy underlined
1    division content the new intern is doing great...
2       sample code the new intern is doing great work
3                 great onboarding process sample code
4    can someone check the broken ac in meeting roo...
5        loving the bold text makes everything cleaner
6      loving the sample code makes everything cleaner
7           wifi is unstable in some zones italic text
8    friday sessions are a great learning opportuni...
9                too many overlapping tasks underlined
Name: cleaned_review, dtype: object

In [30]:
reviews.head()

,employee_name,review,cleaned_review
0,Scarlett,So happy with the hybrid work policy! <u>under...,so happy with the hybrid work policy underlined
1,Chloe,<div>division content</div> The new intern is ...,division content the new intern is doing great...
2,Logan,<code>sample code</code> The new intern is doi...,sample code the new intern is doing great work
3,Nina,Great onboarding process! <code>sample code</c...,great onboarding process sample code
4,Emily,Can someone check the broken AC in meeting roo...,can someone check the broken ac in meeting roo...