In [1]:
import pandas as pd

In [2]:
reviews = pd.read_csv("../data/employee_reviews.csv")
reviews.head()

  Employee Name                                             Review
0      Scarlett  So happy with the hybrid work policy! <u>under...
1         Chloe  <div>division content</div> The new intern is ...
2         Logan  <code>sample code</code> The new intern is doi...
3          Nina  Great onboarding process! <code>sample code</c...
4         Emily  Can someone check the broken AC in meeting roo...

In [3]:
#rename the columns 
reviews.columns = ['employee_name', 'review']
reviews.head()

  employee_name                                             review
0      Scarlett  So happy with the hybrid work policy! <u>under...
1         Chloe  <div>division content</div> The new intern is ...
2         Logan  <code>sample code</code> The new intern is doi...
3          Nina  Great onboarding process! <code>sample code</c...
4         Emily  Can someone check the broken AC in meeting roo...

<b>Tasks:</b>
1. HTML tags
2. URLs
3. Punctuations (!?)
4. Extra spaces
5. Emoji
6. Captial case (convert everything into lower case)

In [4]:
import re

def clean_text(text):
    # 1. remove HTML tags
    text = re.sub(r'<.*?>', '', text)
    
    #2. remove URLS
    text = re.sub(r'http\S+|www\.\S+', '', text)
    
    #3. remove punctuations and emoji
    text = re.sub(r'[^A-Za-z\s]', '', text) # ^ means except and \s means whitespace
    
    #4. remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip() #strip removes the whitespace at the beginning and end
    
    #5. remove emoji already at 3
    
    #6. lower case itttt
    text = str(text).lower()
    
    return text

In [5]:
reviews['cleaned_review'] = reviews['review'].apply(clean_text)
print(reviews['cleaned_review'].iloc[:10])

0      so happy with the hybrid work policy underlined
1    division content the new intern is doing great...
2       sample code the new intern is doing great work
3                 great onboarding process sample code
4    can someone check the broken ac in meeting roo...
5        loving the bold text makes everything cleaner
6      loving the sample code makes everything cleaner
7           wifi is unstable in some zones italic text
8    friday sessions are a great learning opportuni...
9                too many overlapping tasks underlined
Name: cleaned_review, dtype: object

In [6]:
reviews.head()

,employee_name,review,cleaned_review
0,Scarlett,So happy with the hybrid work policy! <u>under...,so happy with the hybrid work policy underlined
1,Chloe,<div>division content</div> The new intern is ...,division content the new intern is doing great...
2,Logan,<code>sample code</code> The new intern is doi...,sample code the new intern is doing great work
3,Nina,Great onboarding process! <code>sample code</c...,great onboarding process sample code
4,Emily,Can someone check the broken AC in meeting roo...,can someone check the broken ac in meeting roo...

In [7]:
#tokenize the clean data
from nltk.tokenize import word_tokenize
reviews['tokens'] = reviews['cleaned_review'].apply(word_tokenize)
reviews.head(10)

,employee_name,review,cleaned_review,tokens
0,Scarlett,So happy with the hybrid work policy! <u>under...,so happy with the hybrid work policy underlined,"[so, happy, with, the, hybrid, work, policy, u..."
1,Chloe,<div>division content</div> The new intern is ...,division content the new intern is doing great...,"[division, content, the, new, intern, is, doin..."
2,Logan,<code>sample code</code> The new intern is doi...,sample code the new intern is doing great work,"[sample, code, the, new, intern, is, doing, gr..."
3,Nina,Great onboarding process! <code>sample code</c...,great onboarding process sample code,"[great, onboarding, process, sample, code]"
4,Emily,Can someone check the broken AC in meeting roo...,can someone check the broken ac in meeting roo...,"[can, someone, check, the, broken, ac, in, mee..."
5,Ava,Loving the <b>bold text</b> – makes everything...,loving the bold text makes everything cleaner,"[loving, the, bold, text, makes, everything, c..."
6,Amelia,Loving the <code>sample code</code> – makes ev...,loving the sample code makes everything cleaner,"[loving, the, sample, code, makes, everything,..."
7,Harper,WiFi is unstable in some zones <i>italic text</i>,wifi is unstable in some zones italic text,"[wifi, is, unstable, in, some, zones, italic, ..."
8,Daniel,Friday sessions are a great learning opportuni...,friday sessions are a great learning opportuni...,"[friday, sessions, are, a, great, learning, op..."
9,Mason,Too many overlapping tasks <u>underlined</u>,too many overlapping tasks underlined,"[too, many, overlapping, tasks, underlined]"